#PBS -j eo
#PBS -l mppwidth=48
#PBS -q debug

set -x
export OMP_NUM_THREADS=1

source /project/projectdirs/m779/python-mpi/activate.sh /dev/shm/local "aprun -n 48 -d 1"

cd $PBS_O_WORKDIR

# send the anaconda packages
bcast -v /project/projectdirs/m779/python-mpi/2.7-anaconda.tar.gz 

# location of MPI4PY locally, 
# must be compatible with the one in 2.7-anaconda.tar.gz
export MPI4PY=/usr/common/usg/python/2.7-anaconda/lib/python2.7/site-packages/mpi4py

bcast -v testpkg.tar.gz

time aprun -n 48 -d 1 $MPI4PY/bin/python-mpi /dev/shm/local/testpkg/main.py
