#PBS -j eo
#PBS -l mppwidth=24
#PBS -q debug

cd $PBS_O_WORKDIR
export OMP_NUM_THREADS=1

export PYTHON_MPI_CHROOT=/dev/shm
export PYTHON_MPI_PKGROOT=/project/projectdirs/m779/python-mpi/usg
export PYTHON_MPI_PACKAGES=matplotlib-1.4.3.tar.gz:mpi4py-1.3.1.tar.gz:numpy-1.9.2.tar.gz:python-2.7.9.tar.gz:scipy-0.15.1.tar.gz:yfeng1-local-05132015.tar.gz

time aprun -n 24 -d 1 /project/projectdirs/m779/python-mpi/python-mpi -c 'import scipy; print scipy'

